Repository zalando-incubator/kube-ingress-aws-controller, pull requests merged in 2024-02, with the labels that each got.

#679 Set the default ingress API Version
  controller.go
Labels: bugfix

#681 testsuit: add test case for flags
  controller_test.go
Labels: minor

#682 fix: disabling NLB cross zone load balancing had no effect on current NLBs
  aws/cf_template.go
  aws/cf_template_test.go
  testdata/ingress_nlb/output/templates/ing.cf
  testdata/ingress_rg_shared_nlb/output/templates/shared.cf
  testdata/rg_nlb/output/templates/rg.cf
Labels: minor, bugfix
