Repository zalando-incubator/kube-ingress-aws-controller, pull requests merged in 2024-06, with the labels that each got.

#704 deploy: use static base image
  delivery.yaml
Labels: architectural

#705 build: use correct version for multiarch image
  controller.go
  delivery.yaml
Labels: minor

#706 chore(deps): update k8s.io/* to v0.30.2
  go.mod
  go.sum
Labels: dependencies
