Repository zalando-incubator/kube-ingress-aws-controller, pull requests merged in 2025-07, with the labels that each got.

#748 ingress-controller: update ingresses only if the load balancer is active
  .github/workflows/ci.yaml
  .gitignore
  aws/adapter.go
  aws/adapter_test.go
  aws/cf.go
  aws/cf_template.go
  aws/cf_template_test.go
  aws/cloudwatch.go
  aws/cloudwatch_test.go
  aws/elbv2.go
  aws/elbv2_test.go
  aws/fake/elbv2.go
  cloudformation.md
  testdata/ing_shared_rg_notshared_alb/output/templates/01-ing.cf
  testdata/ing_shared_rg_notshared_alb/output/templates/02-rg.cf
  testdata/ingress_alb/output/templates/ing.cf
  testdata/ingress_nlb/output/templates/ing.cf
  testdata/ingress_rg_shared_alb/output/templates/shared.cf
  testdata/ingress_rg_shared_nlb/output/templates/shared.cf
  testdata/rg_alb/output/templates/rg.cf
  testdata/rg_nlb/output/templates/rg.cf
  worker.go
  worker_test.go
Labels: bugfix

#757 aws: sort subnets in Adapter.FindLBSubnets
  aws/adapter.go
  aws/adapter_test.go
Labels: minor

#758 Add worker type
  controller.go
  metrics.go
  worker.go
  worker_test.go
Labels: refactor, minor
